[package]
name = "doublecover_rust"
version = "0.1.0"
authors = ["Paul Tabatabai <tabatabai@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
